artifacts_root : artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: https://github.com/AnkitSangode/JavaScriptMiniProjects/raw/refs/heads/main/Chicken-fecal-images.zip
  local_data_path: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

prepare_base_model:
  root_dir: artifacts/prepare_base_model
  base_model_path: artifacts/prepare_base_model/base_model.keras 
  updated_base_model_path: artifacts/prepare_base_model/updated_base_model.keras 